export { splitSegments } from './dom/split';
export { prefersReducedMotion } from './motion';
export { createSplitText, SEGMENT_SELECTOR } from './animation/split-text';
export type { SplitTextController } from './animation/split-text';
export { splitTextSchema, splitTextMeta } from './schemas/split-text';
export type { SplitTextProps, SplitTextOptions } from './schemas/split-text';
export { propsTable } from './props-table';
export type { PropDoc } from './props-table';
export { installInfo, REGISTRY_BASE } from './registry';
export type { InstallInfo, InstallTab, Framework } from './registry';
export { JOLT_ORIGIN } from './origin';
export { blurInSchema, blurInMeta } from './schemas/blur-in';
export type { BlurInProps } from './schemas/blur-in';
export { waveSchema, waveMeta } from './schemas/wave';
export type { WaveProps } from './schemas/wave';
export { gradientTextSchema, gradientTextMeta } from './schemas/gradient-text';
export type { GradientTextProps } from './schemas/gradient-text';
export { shinyTextSchema, shinyTextMeta } from './schemas/shiny-text';
export type { ShinyTextProps } from './schemas/shiny-text';
export { typewriterSchema, typewriterMeta } from './schemas/typewriter';
export type { TypewriterProps } from './schemas/typewriter';
export { rotatingWordsSchema, rotatingWordsMeta } from './schemas/rotating-words';
export type { RotatingWordsProps } from './schemas/rotating-words';
export { createCountUp, formatNumber } from './animation/count-up';
export type { CountUpController } from './animation/count-up';
export { countUpSchema, countUpMeta } from './schemas/count-up';
export type { CountUpProps, CountUpOptions } from './schemas/count-up';
export { createScramble } from './animation/scramble';
export type { ScrambleController } from './animation/scramble';
export { scrambleSchema, scrambleMeta } from './schemas/scramble';
export type { ScrambleProps, ScrambleOptions } from './schemas/scramble';
export { createScrollVelocity, SCROLL_VELOCITY_TRACK } from './animation/scroll-velocity';
export type { ScrollVelocityController } from './animation/scroll-velocity';
export { scrollVelocitySchema, scrollVelocityMeta } from './schemas/scroll-velocity';
export type { ScrollVelocityProps, ScrollVelocityOptions } from './schemas/scroll-velocity';
export { particlesSchema, particlesMeta } from './schemas/particles';
export type { ParticlesProps, ParticlesOptions } from './schemas/particles';
export { wavesSchema, wavesMeta } from './schemas/waves';
export type { WavesProps, WavesOptions } from './schemas/waves';
export { dotsSchema, dotsMeta } from './schemas/dots';
export type { DotsProps, DotsOptions } from './schemas/dots';
export { globeSchema, globeMeta } from './schemas/globe';
export type { GlobeProps, GlobeOptions } from './schemas/globe';
export { ringsSchema, ringsMeta } from './schemas/rings';
export type { RingsProps, RingsOptions } from './schemas/rings';
export { auroraSchema, auroraMeta } from './schemas/aurora';
export type { AuroraProps, AuroraOptions } from './schemas/aurora';
export { spinnerSchema, spinnerMeta } from './schemas/spinner';
export type { SpinnerProps } from './schemas/spinner';
export { dotBounceSchema, dotBounceMeta } from './schemas/dot-bounce';
export type { DotBounceProps } from './schemas/dot-bounce';
export { barsSchema, barsMeta } from './schemas/bars';
export type { BarsProps } from './schemas/bars';
// gen:exports — scripts/gen-component.mjs appends new schema/meta exports above this line
