export { splitSegments } from './dom/split';
export { prefersReducedMotion } from './motion';
export { createSplitText, SEGMENT_SELECTOR } from './animation/split-text';
export type { SplitTextController } from './animation/split-text';
export { splitTextSchema, splitTextMeta } from './schemas/split-text';
export type { SplitTextProps, SplitTextOptions } from './schemas/split-text';
export { propsTable } from './props-table';
export type { PropDoc } from './props-table';
export { blurInSchema, blurInMeta } from './schemas/blur-in';
export type { BlurInProps } from './schemas/blur-in';
export { waveSchema, waveMeta } from './schemas/wave';
export type { WaveProps } from './schemas/wave';
